import { useState, useEffect } from 'react';
import api from '../services/api';
import ReactMarkdown from 'react-markdown';
import { Loader2, Sparkles, RefreshCw } from 'lucide-react';
import { motion } from 'framer-motion';

export default function Roadmap() {
  const [roadmap, setRoadmap] = useState('');
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    let isMounted = true;

    const fetchLatestRoadmap = async () => {
      try {
        const res = await api.get('/roadmap/latest');
        if (isMounted) {
          setRoadmap(res.data.roadmap_text);
        }
      } catch (err) {
        if (isMounted && err.response?.status !== 404) {
          setError('Failed to load roadmap');
        }
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    };

    fetchLatestRoadmap();

    return () => {
      isMounted = false;
    };
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    setError('');
    try {
      const res = await api.post('/roadmap/');
      setRoadmap(res.data.roadmap_text);
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate roadmap');
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-[calc(100vh-4rem)]">
        <Loader2 className="animate-spin h-8 w-8 text-primary-500" />
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <Sparkles className="h-8 w-8 text-yellow-400" />
            AI Career Roadmap
          </h1>
          <p className="text-textMuted mt-1">Your personalized path to success generated by Groq AI</p>
        </div>
        
        <button 
          onClick={handleGenerate} 
          disabled={generating}
          className="btn-primary flex items-center gap-2 whitespace-nowrap"
        >
          {generating ? <Loader2 className="animate-spin h-5 w-5" /> : <RefreshCw className="h-5 w-5" />}
          {roadmap ? 'Regenerate Roadmap' : 'Generate Roadmap'}
        </button>
      </div>

      {error && <div className="bg-red-500/10 border border-red-500/50 text-red-500 px-4 py-3 rounded-lg mb-6">{error}</div>}

      {!roadmap && !generating && !error && (
        <div className="glass-card p-12 text-center">
          <Sparkles className="h-16 w-16 text-yellow-500/50 mx-auto mb-4" />
          <h3 className="text-xl font-semibold mb-2">No Roadmap Generated</h3>
          <p className="text-textMuted mb-6">Generate your first AI-powered career roadmap based on your latest prediction.</p>
          <button onClick={handleGenerate} className="btn-primary">Generate Now</button>
        </div>
      )}

      {generating && (
        <div className="glass-card p-12 text-center flex flex-col items-center justify-center min-h-[400px]">
          <Loader2 className="animate-spin h-12 w-12 text-primary-500 mb-4" />
          <h3 className="text-xl font-semibold mb-2">AI is analyzing your profile...</h3>
          <p className="text-textMuted">Crafting a personalized 4-month strategy. This might take a few seconds.</p>
        </div>
      )}

      {roadmap && !generating && (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-card p-8 prose prose-invert max-w-none prose-h3:text-primary-400 prose-a:text-primary-500 hover:prose-a:text-primary-400 prose-ul:list-disc prose-ol:list-decimal"
        >
          <ReactMarkdown>{roadmap}</ReactMarkdown>
        </motion.div>
      )}
    </div>
  );
}
